name: CustomBar
author: SuperKali
version: 1.2
api:
- '3.0.0-ALPHA9'
- '3.0.0-ALPHA10'
main: CustomBar\Main
description: Custom bar for your server!
github: https://github.com/SuperKali/CustomBar
